
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\MAX7219PSU\max7219psu.h"

// -*-*- List of node objects -*-*-
nBlock_MAX7219PSU      nb_nBlockNode0_MAX7219PSU (p5, p6, p7, p8, 8, 7);

// -*-*- List of connection objects -*-*-


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
